services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/insurance
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_API_KEY=${ADMIN_API_KEY}
    depends_on:
      db:
        condition: service_healthy
      elastic:
        condition: service_healthy
    volumes:
      - ./src/:/app/src/
  db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=insurance
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d insurance" ]
      interval: 5s
      timeout: 5s
      retries: 5

  #single-node cluster, to change to multi-node, comment elastic service, and uncomment es01, es02, and if needed kibana
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.1
    mem_limit: 1GB
    environment:
      - "xpack.security.enabled=false"
      - "transport.host=127.0.0.1"
    ports:
      - "127.0.0.1:9200:9200"
    healthcheck:
      test: "curl -X GET http://localhost:9200/_cluster/health || exit 1"
      interval: 5s
      timeout: 2s
      retries: 20
  # es01:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:9.2.1
  #   mem_limit: 1GB
  #   environment:
  #     - "xpack.security.enabled=false"
  #     - node.name=es01
  #     - cluster.name=docker-cluster
  #     - cluster.initial_master_nodes=es01,es02
  #     - discovery.seed_hosts=es02
  #   ports:
  #     - "127.0.0.1:9200:9200"
  #   healthcheck:
  #     test: "curl -X GET http://localhost:9200/_cluster/health || exit 1"
  #     interval: 5s
  #     timeout: 2s
  #     retries: 20
  # es02:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:9.2.1
  #   mem_limit: 1GB
  #   environment:
  #     - "xpack.security.enabled=false"
  #     - node.name=es02
  #     - cluster.name=docker-cluster
  #     - cluster.initial_master_nodes=es01,es02
  #     - discovery.seed_hosts=es01
  #   healthcheck:
  #     test: "curl -X GET http://localhost:9200/_cluster/health || exit 1"
  #     interval: 5s
  #     timeout: 2s
  #     retries: 20

  # kibana:
  #   depends_on:
  #     es01:
  #       condition: service_healthy
  #     es02:
  #       condition: service_healthy
  #   image: docker.elastic.co/kibana/kibana:9.2.1
  #   ports:
  #     - 127.0.0.1:5601:5601
  #   environment:
  #     - SERVERNAME=kibana
  #     - ELASTICSEARCH_HOSTS=http://es01:9200
  #     - "xpack.security.enabled=false"
  #   mem_limit: 1GB
  #   healthcheck:
  #     test: [ "CMD-SHELL", "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'" ]
  #     interval: 10s
  #     timeout: 10s
  #     retries: 120
