version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/insurance
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_API_KEY=${ADMIN_API_KEY}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src/:/app/src/
  db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=insurance
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d insurance" ]
      interval: 5s
      timeout: 5s
      retries: 5

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.1
    mem_limit: 1GB
    environment:
      - "transport.host=127.0.0.1"
      - "xpack.security.enabled=false"
    ports:
      - "9200:9200"
